// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXtxctg7Ot6UlqeGO_9jLbp-3wn1O4q4',
    appId: '1:314318645760:android:ded1e415a70b9181c506e5',
    messagingSenderId: '314318645760',
    projectId: 'nutrifit-4f82c',
    storageBucket: 'nutrifit-4f82c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOm_MF1y_QsoqGa00RZBvn7lhqv-J7q0',
    appId: '1:314318645760:ios:15ecb14be4919bcec506e5',
    messagingSenderId: '314318645760',
    projectId: 'nutrifit-4f82c',
    storageBucket: 'nutrifit-4f82c.firebasestorage.app',
    iosBundleId: 'com.example.nutrifit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOm_MF1y_QsoqGa00RZBvn7lhqv-J7q0',
    appId: '1:314318645760:ios:15ecb14be4919bcec506e5',
    messagingSenderId: '314318645760',
    projectId: 'nutrifit-4f82c',
    storageBucket: 'nutrifit-4f82c.firebasestorage.app',
    iosBundleId: 'com.example.nutrifit',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoej7c9rUQCPLOS07SYaVKwK6VJeZBGA',
    appId: '1:314318645760:web:c32f5f3143f7d21ac506e5',
    messagingSenderId: '314318645760',
    projectId: 'nutrifit-4f82c',
    authDomain: 'nutrifit-4f82c.firebaseapp.com',
    storageBucket: 'nutrifit-4f82c.firebasestorage.app',
    measurementId: 'G-7K9WG95GME',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVoej7c9rUQCPLOS07SYaVKwK6VJeZBGA',
    appId: '1:314318645760:web:f54479b07beb9382c506e5',
    messagingSenderId: '314318645760',
    projectId: 'nutrifit-4f82c',
    authDomain: 'nutrifit-4f82c.firebaseapp.com',
    storageBucket: 'nutrifit-4f82c.firebasestorage.app',
    measurementId: 'G-HGEJL88J7B',
  );

}