// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJqc8RQQFB9BJuSvxpxtLg8fp1R7V4jo',
    appId: '1:114848525815:android:cf7ccbd40e0bb6f94a12f2',
    messagingSenderId: '114848525815',
    projectId: 'nutrimove-8703e',
    storageBucket: 'nutrimove-8703e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqln-tVhmTek9Lwo5OBGECSua4mimSJQ',
    appId: '1:114848525815:ios:dec322f8c637d36b4a12f2',
    messagingSenderId: '114848525815',
    projectId: 'nutrimove-8703e',
    storageBucket: 'nutrimove-8703e.firebasestorage.app',
    iosBundleId: 'com.example.nutrimove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqln-tVhmTek9Lwo5OBGECSua4mimSJQ',
    appId: '1:114848525815:ios:dec322f8c637d36b4a12f2',
    messagingSenderId: '114848525815',
    projectId: 'nutrimove-8703e',
    storageBucket: 'nutrimove-8703e.firebasestorage.app',
    iosBundleId: 'com.example.nutrimove',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSuYmvz7eralCY9svuTkzLpPLkXQ1MiY',
    appId: '1:114848525815:web:bc8a71508ab56f8b4a12f2',
    messagingSenderId: '114848525815',
    projectId: 'nutrimove-8703e',
    authDomain: 'nutrimove-8703e.firebaseapp.com',
    storageBucket: 'nutrimove-8703e.firebasestorage.app',
    measurementId: 'G-LBBQKKCTC9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJSuYmvz7eralCY9svuTkzLpPLkXQ1MiY',
    appId: '1:114848525815:web:24383abf10ff14e84a12f2',
    messagingSenderId: '114848525815',
    projectId: 'nutrimove-8703e',
    authDomain: 'nutrimove-8703e.firebaseapp.com',
    storageBucket: 'nutrimove-8703e.firebasestorage.app',
    measurementId: 'G-E41P3D6CJB',
  );

}